import { NavBar } from "@/components/navbar";
import { poppins } from "@/font/Poppins";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-main-background`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
