'use client'
import { NavBar } from "@/components/navbar";
import { poppins } from "@/font/Poppins";
import "../globals.css";
import { signOut } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  async function logout() {
    try {
      await signOut();
    } catch (error) {
      // display error message to user
      console.error("Something went wrong with your login.");
    }
  }
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-100`}>
        <NavBar logout={logout} />
        {children}
      </body>
    </html>
  );
}
