import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header></header>
      <body className={inter.className}>
        <h1 className="text-[#fff]">header da aplicação</h1>
        {children}
      </body>
    </html>
  );
}
